app: 
  name: go-starterkit
  version: v1.0.0 

server: 
  host: 0.0.0.0 
  port: 8080 

database: 
  migration: 
    path: schema/migrations
  postgres: 
    driver: postgres
    write:
      hostname: localhost
      dbname: try_db
      username: postgres
      password: password 
    read: 
      hostname: localhost
      dbname: try_db
      username: postgres
      password: password
  mysql: 
    driver: mysql
    write:
      hostname: localhost
      dbname: try_db
      username: user
      password: password
  sqlserver: 
    driver: sqlserver 
    write: 
      connection: server={hostname} user={username} password={password} dbname={dbname} port=1443 target_session_attrs=read-write sslmode=disable 
      hostname:  
      dbname:  
      username:  
      password:  
    read: 
      connection: host={hostname} user={username} password={password} dbname={dbname} port=1443 target_session_attrs=read-write sslmode=disable 
      hostname: 
      dbname: 
      username: 
      password: 

telemetry: 
  enable: true 
  jaeger: 
    trace_ratio: 1 
    agent_host: 127.0.0.1
    agent_port: 6831 

internalapi: 
  web: 
    baseurl: http://00.000.0.000:1433/ 
    timeout: 30 
    check-status-delay: 20 
    check-status-count: 3