# version: '3' 
services: 
  jaeger: 
    image: jaegertracing/all-in-one:1.21 
    ports: 
      - 14268:14268 
      - 16686:16686 
      - 6831:6831/udp 
    environment: 
      SPAN_STORAGE_TYPE: badger 
      BADGER_EPHEMERAL: "false" 
      BADGER_DIRECTORY_KEY: /badger/key 
      BADGER_DIRECTORY_VALUE: /badger/data
  postgres: 
    image: postgres
    ports: 
      - 5432:5432 
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: try_db 
    networks: 
      - app-tier
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'try_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    # volumes:
    #   - my-db:/var/lib/mysql
# Names our volume
# volumes:
#   my-db:

networks:
  app-tier: 
    driver: bridge