version: '3' 
services: 
  jaeger: 
    image: jaegertracing/all-in-one:1.21 
    ports: 
      - 14268:14268 
      - 16686:16686 
      - 6831:6831/udp 
    environment: 
      SPAN_STORAGE_TYPE: badger 
      BADGER_EPHEMERAL: "false" 
      BADGER_DIRECTORY_KEY: /badger/key 
      BADGER_DIRECTORY_VALUE: /badger/data
  postgres: 
    image: postgres
    ports: 
      - 5432:5432 
    -d
    networks: 
      - app-tier

networks:
  app-tier: 
    driver: bridge